//
//  DummyData.swift
//  OddsiumCT
//
//  Created by Johan Wejdenstolpe on 2023-02-06.
//

import Foundation

let dummyData = """
{
    "data": {
        "identifier": "matches",
        "matches": [
            {
                "id": 316224,
                "name": "Atlante - Pumas Tabasco",
                "date": "2022-02-25T00:00:00Z",
                "tournament_id": 1783,
                "tournament_name": "Liga de Expansión MX",
                "tournament_flag_url": "c/250.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Atlante",
                "ht_id": 12387,
                "ht_flag_url": "t/12387_134.png",
                "at_name": "Pumas Tabasco",
                "at_id": 48346,
                "at_flag_url": "t/48346.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316250,
                "name": "Academia Puerto Cabello - Portuguesa FC",
                "date": "2022-02-25T00:15:00Z",
                "tournament_id": 2183,
                "tournament_name": "Primera Division",
                "tournament_flag_url": "c/369.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Academia Puerto Cabello",
                "ht_id": 42503,
                "ht_flag_url": "t/42503.png",
                "at_name": "Portuguesa FC",
                "at_id": 32383,
                "at_flag_url": "t/32383_683.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316203,
                "name": "Campinense PB - Sao Paulo",
                "date": "2022-02-25T01:30:00Z",
                "tournament_id": 1166,
                "tournament_name": "Copa do Brasil",
                "tournament_flag_url": "c/136.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Campinense PB",
                "ht_id": 15252,
                "ht_flag_url": "t/15252_597.png",
                "at_name": "Sao Paulo",
                "at_id": 34755,
                "at_flag_url": "t/34755.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316202,
                "name": "Huracan - Velez Sarsfield",
                "date": "2022-02-25T01:30:00Z",
                "tournament_id": 2959,
                "tournament_name": "Primera División",
                "tournament_flag_url": "c/112.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Huracan",
                "ht_id": 23218,
                "ht_flag_url": "t/23218.png",
                "at_name": "Velez Sarsfield",
                "at_id": 39809,
                "at_flag_url": "t/39809.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316384,
                "name": "Pachuca - Mazatlan",
                "date": "2022-02-25T02:00:00Z",
                "tournament_id": 2976,
                "tournament_name": "Liga MX",
                "tournament_flag_url": "c/250.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Pachuca",
                "ht_id": 31086,
                "ht_flag_url": "t/31086.png",
                "at_name": "Mazatlan",
                "at_id": 47460,
                "at_flag_url": "t/47460.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316385,
                "name": "Queretaro - Toluca",
                "date": "2022-02-25T04:05:00Z",
                "tournament_id": 2976,
                "tournament_name": "Liga MX",
                "tournament_flag_url": "c/250.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Queretaro",
                "ht_id": 32779,
                "ht_flag_url": "t/32779.png",
                "at_name": "Toluca",
                "at_id": 38313,
                "at_flag_url": "t/th_38313_517.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316345,
                "name": "Brisbane Roar - Melbourne Victory",
                "date": "2022-02-25T09:55:00Z",
                "tournament_id": 1079,
                "tournament_name": "A-League",
                "tournament_flag_url": "c/118.png",
                "status": "Postponed",
                "live_status": "",
                "ht_name": "Brisbane Roar",
                "ht_id": 14655,
                "ht_flag_url": "t/14655.png",
                "at_name": "Melbourne Victory",
                "at_id": 28129,
                "at_flag_url": "t/28129.png",
                "score": {
                    "ht_score": "",
                    "at_score": "",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 317857,
                "name": "Lillestrøm - Tromsø IL",
                "date": "2022-02-25T12:00:00Z",
                "tournament_id": 1383,
                "tournament_name": "Club Friendlies",
                "tournament_flag_url": "c/177.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Lillestrøm",
                "ht_id": 26455,
                "ht_flag_url": "t/26455.png",
                "at_name": "Tromsø IL",
                "at_id": 38701,
                "at_flag_url": "t/38701.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316436,
                "name": "Hồng Lĩnh Hà Tĩnh - Hải Phòng",
                "date": "2022-02-25T12:00:00Z",
                "tournament_id": 3358,
                "tournament_name": "V League 1",
                "tournament_flag_url": "c/371.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Hồng Lĩnh Hà Tĩnh",
                "ht_id": 46961,
                "ht_flag_url": "t/46961.png",
                "at_name": "Hải Phòng",
                "at_id": 22111,
                "at_flag_url": "t/22111.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316858,
                "name": "Sofapaka - Tusker",
                "date": "2022-02-25T13:00:00Z",
                "tournament_id": 2741,
                "tournament_name": "Premier League",
                "tournament_flag_url": "c/227.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Sofapaka",
                "ht_id": 36158,
                "ht_flag_url": "t/th_36158_583.png",
                "at_name": "Tusker",
                "at_id": 38894,
                "at_flag_url": "t/0001_odds_logo80.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316426,
                "name": "Minai - Zorya Lugansk",
                "date": "2022-02-25T13:00:00Z",
                "tournament_id": 2999,
                "tournament_name": "Premier League",
                "tournament_flag_url": "c/364.png",
                "status": "Postponed",
                "live_status": "",
                "ht_name": "Minai",
                "ht_id": 48200,
                "ht_flag_url": "t/48200.png",
                "at_name": "Zorya Lugansk",
                "at_id": 41614,
                "at_flag_url": "t/41614.png",
                "score": {
                    "ht_score": "",
                    "at_score": "",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316356,
                "name": "Lokomotiv Plovdiv - Tsarsko selo",
                "date": "2022-02-25T14:00:00Z",
                "tournament_id": 1266,
                "tournament_name": "A PFG",
                "tournament_flag_url": "c/141.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Lokomotiv Plovdiv",
                "ht_id": 26699,
                "ht_flag_url": "t/26699.png",
                "at_name": "Tsarsko selo",
                "at_id": 42423,
                "at_flag_url": "t/42423.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316509,
                "name": "Radnicki 1923 Kragujevac - Vozdovac",
                "date": "2022-02-25T14:00:00Z",
                "tournament_id": 2993,
                "tournament_name": "Super Liga",
                "tournament_flag_url": "c/326.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Radnicki 1923 Kragujevac",
                "ht_id": 32870,
                "ht_flag_url": "t/32870.png",
                "at_name": "Vozdovac",
                "at_id": 40435,
                "at_flag_url": "t/40435.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316381,
                "name": "Ironi Rishon Lezion - Ironi Ramat Hasharon",
                "date": "2022-02-25T14:00:00Z",
                "tournament_id": 3007,
                "tournament_name": "Liga Leumit",
                "tournament_flag_url": "c/220.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Ironi Rishon Lezion",
                "ht_id": 23765,
                "ht_flag_url": "t/23765.png",
                "at_name": "Ironi Ramat Hasharon",
                "at_id": 23763,
                "at_flag_url": "t/23763_195.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316380,
                "name": "Hapoel Ramat Gan - Hapoel Petach Tikva",
                "date": "2022-02-25T14:00:00Z",
                "tournament_id": 3007,
                "tournament_name": "Liga Leumit",
                "tournament_flag_url": "c/220.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Hapoel Ramat Gan",
                "ht_id": 22343,
                "ht_flag_url": "t/22343.png",
                "at_name": "Hapoel Petach Tikva",
                "at_id": 41766,
                "at_flag_url": "t/th_41766_681.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316428,
                "name": "Khorfakkan - Al Nasr",
                "date": "2022-02-25T14:30:00Z",
                "tournament_id": 2297,
                "tournament_name": "UAE Pro-League",
                "tournament_flag_url": "c/360.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Khorfakkan",
                "ht_id": 48579,
                "ht_flag_url": "t/48579.png",
                "at_name": "Al Nasr",
                "at_id": 10866,
                "at_flag_url": "t/10866_759.png",
                "score": {
                    "ht_score": "4",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316427,
                "name": "Emirates - Al Jazira",
                "date": "2022-02-25T14:30:00Z",
                "tournament_id": 2297,
                "tournament_name": "UAE Pro-League",
                "tournament_flag_url": "c/360.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Emirates",
                "ht_id": 18865,
                "ht_flag_url": "t/18865_105.png",
                "at_name": "Al Jazira",
                "at_id": 10811,
                "at_flag_url": "t/10811_730.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "3",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 315837,
                "name": "US Biskra - RC Arba",
                "date": "2022-02-25T14:30:00Z",
                "tournament_id": 2387,
                "tournament_name": "Ligue 1",
                "tournament_flag_url": "c/108.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "US Biskra",
                "ht_id": 39392,
                "ht_flag_url": "t/th_39392_763.png",
                "at_name": "RC Arba",
                "at_id": 33107,
                "at_flag_url": "t/33107_440.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 315840,
                "name": "JS Kabilye - Olympique de Médéa",
                "date": "2022-02-25T15:00:00Z",
                "tournament_id": 2387,
                "tournament_name": "Ligue 1",
                "tournament_flag_url": "c/108.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "JS Kabilye",
                "ht_id": 24386,
                "ht_flag_url": "t/24386_213.png",
                "at_name": "Olympique de Médéa",
                "at_id": 30362,
                "at_flag_url": "t/30362_780.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 315842,
                "name": "AsM Oran - CS Constantine",
                "date": "2022-02-25T15:00:00Z",
                "tournament_id": 2387,
                "tournament_name": "Ligue 1",
                "tournament_flag_url": "c/108.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "AsM Oran",
                "ht_id": 12256,
                "ht_flag_url": "t/12256_931.png",
                "at_name": "CS Constantine",
                "at_id": 17009,
                "at_flag_url": "t/th_17009_290.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 315841,
                "name": "NC Magra - WA Tlemcen",
                "date": "2022-02-25T15:00:00Z",
                "tournament_id": 2387,
                "tournament_name": "Ligue 1",
                "tournament_flag_url": "c/108.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "NC Magra",
                "ht_id": 42508,
                "ht_flag_url": "t/42508.png",
                "at_name": "WA Tlemcen",
                "at_id": 40516,
                "at_flag_url": "t/th_40516_443.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 317860,
                "name": "Asane - Mjondalen",
                "date": "2022-02-25T16:00:00Z",
                "tournament_id": 1383,
                "tournament_name": "Club Friendlies",
                "tournament_flag_url": "c/177.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Asane",
                "ht_id": 12146,
                "ht_flag_url": "t/12146.png",
                "at_name": "Mjondalen",
                "at_id": 28585,
                "at_flag_url": "t/28585.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 318164,
                "name": "Kristiansund BK - Rosenborg",
                "date": "2022-02-25T16:00:00Z",
                "tournament_id": 1383,
                "tournament_name": "Club Friendlies",
                "tournament_flag_url": "c/177.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Kristiansund BK",
                "ht_id": 25530,
                "ht_flag_url": "t/th_25530_430.png",
                "at_name": "Rosenborg",
                "at_id": 33886,
                "at_flag_url": "t/33886_836.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316510,
                "name": "Mladost Lucani - Proleter Novi Sad",
                "date": "2022-02-25T16:00:00Z",
                "tournament_id": 2993,
                "tournament_name": "Super Liga",
                "tournament_flag_url": "c/326.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Mladost Lucani",
                "ht_id": 28610,
                "ht_flag_url": "t/28610_593.png",
                "at_name": "Proleter Novi Sad",
                "at_id": 42467,
                "at_flag_url": "t/42467.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316511,
                "name": "Radnicki Nis - Novi Pazar",
                "date": "2022-02-25T16:00:00Z",
                "tournament_id": 2993,
                "tournament_name": "Super Liga",
                "tournament_flag_url": "c/326.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Radnicki Nis",
                "ht_id": 32873,
                "ht_flag_url": "t/32873.png",
                "at_name": "Novi Pazar",
                "at_id": 30236,
                "at_flag_url": "t/30236.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316386,
                "name": "Olympique Club Safi - FUS Rabat",
                "date": "2022-02-25T16:00:00Z",
                "tournament_id": 3022,
                "tournament_name": "Botola Pro",
                "tournament_flag_url": "c/246.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Olympique Club Safi",
                "ht_id": 30709,
                "ht_flag_url": "t/30709_220.png",
                "at_name": "FUS Rabat",
                "at_id": 20761,
                "at_flag_url": "t/20761_633.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316357,
                "name": "CSKA Sofia - Botev Vratsa",
                "date": "2022-02-25T16:30:00Z",
                "tournament_id": 1266,
                "tournament_name": "A PFG",
                "tournament_flag_url": "c/141.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "CSKA Sofia",
                "ht_id": 17037,
                "ht_flag_url": "t/17037.png",
                "at_name": "Botev Vratsa",
                "at_id": 14369,
                "at_flag_url": "t/14369.png",
                "score": {
                    "ht_score": "4",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316410,
                "name": "UTA Arad - Academica Clinceni",
                "date": "2022-02-25T16:30:00Z",
                "tournament_id": 1889,
                "tournament_name": "Liga 1",
                "tournament_flag_url": "c/302.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "UTA Arad",
                "ht_id": 47469,
                "ht_flag_url": "t/47469.png",
                "at_name": "Academica Clinceni",
                "at_id": 42460,
                "at_flag_url": "t/42460.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 318165,
                "name": "Ranheim - Nardo",
                "date": "2022-02-25T17:00:00Z",
                "tournament_id": 1383,
                "tournament_name": "Club Friendlies",
                "tournament_flag_url": "c/177.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Ranheim",
                "ht_id": 33010,
                "ht_flag_url": "t/33010.png",
                "at_name": "Nardo",
                "at_id": 29447,
                "at_flag_url": "t/29447_417.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316429,
                "name": "Ittihad Kalba - Al Ain",
                "date": "2022-02-25T17:00:00Z",
                "tournament_id": 2297,
                "tournament_name": "UAE Pro-League",
                "tournament_flag_url": "c/360.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Ittihad Kalba",
                "ht_id": 48601,
                "ht_flag_url": "t/48601.png",
                "at_name": "Al Ain",
                "at_id": 10703,
                "at_flag_url": "t/th_10703_695.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 315836,
                "name": "Aso Chlef - Paradou AC",
                "date": "2022-02-25T17:00:00Z",
                "tournament_id": 2387,
                "tournament_name": "Ligue 1",
                "tournament_flag_url": "c/108.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Aso Chlef",
                "ht_id": 12260,
                "ht_flag_url": "t/12260_873.png",
                "at_name": "Paradou AC",
                "at_id": 41899,
                "at_flag_url": "t/41899_101.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316409,
                "name": "Al Sailiya - Qatar SC",
                "date": "2022-02-25T17:00:00Z",
                "tournament_id": 3014,
                "tournament_name": "Stars League",
                "tournament_flag_url": "c/299.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Al Sailiya",
                "ht_id": 10913,
                "ht_flag_url": "t/th_10913_734.png",
                "at_name": "Qatar SC",
                "at_id": 32728,
                "at_flag_url": "t/32728.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 315102,
                "name": "Omonia Nicosia - Apoel Nicosia",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 1293,
                "tournament_name": "1st  Division",
                "tournament_flag_url": "c/167.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Omonia Nicosia",
                "ht_id": 30747,
                "ht_flag_url": "t/30747_576.png",
                "at_name": "Apoel Nicosia",
                "at_id": 11791,
                "at_flag_url": "t/11791.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "4",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 315103,
                "name": "Pafos - Aris",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 1293,
                "tournament_name": "1st  Division",
                "tournament_flag_url": "c/167.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Pafos",
                "ht_id": 47491,
                "ht_flag_url": "t/47491.png",
                "at_name": "Aris",
                "at_id": 11941,
                "at_flag_url": "t/11941_652.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316438,
                "name": "Sandnes Ulf - Jerv",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 1383,
                "tournament_name": "Club Friendlies",
                "tournament_flag_url": "c/177.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Sandnes Ulf",
                "ht_id": 34560,
                "ht_flag_url": "t/34560.png",
                "at_name": "Jerv",
                "at_id": 24153,
                "at_flag_url": "t/24153.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 317861,
                "name": "Naestved - Frem",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 1383,
                "tournament_name": "Club Friendlies",
                "tournament_flag_url": "c/177.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Naestved",
                "ht_id": 29327,
                "ht_flag_url": "t/th_29327_575.png",
                "at_name": "Frem",
                "at_id": 20642,
                "at_flag_url": "t/th_20642_962.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316404,
                "name": "Zaglebie Sosnowiec - Odra Opole",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 2089,
                "tournament_name": "I Liga",
                "tournament_flag_url": "c/295.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Zaglebie Sosnowiec",
                "ht_id": 41393,
                "ht_flag_url": "t/41393_343.png",
                "at_name": "Odra Opole",
                "at_id": 30456,
                "at_flag_url": "t/30456_695.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 315844,
                "name": "USM Alger - NA Hussein-Dey",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 2387,
                "tournament_name": "Ligue 1",
                "tournament_flag_url": "c/108.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "USM Alger",
                "ht_id": 39429,
                "ht_flag_url": "t/39429_347.png",
                "at_name": "NA Hussein-Dey",
                "at_id": 29278,
                "at_flag_url": "t/29278_386.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316424,
                "name": "Trabzonspor - Kayserispor",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 2956,
                "tournament_name": "Super League",
                "tournament_flag_url": "c/356.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Trabzonspor",
                "ht_id": 38528,
                "ht_flag_url": "t/38528.png",
                "at_name": "Kayserispor",
                "at_id": 24828,
                "at_flag_url": "t/24828.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316423,
                "name": "Adana Demirspor - Antalyaspor",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 2956,
                "tournament_name": "Super League",
                "tournament_flag_url": "c/356.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Adana Demirspor",
                "ht_id": 10308,
                "ht_flag_url": "t/10308_349.png",
                "at_name": "Antalyaspor",
                "at_id": 11724,
                "at_flag_url": "t/11724.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316402,
                "name": "Rakow Czestochowa - Wisla Plock",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 2963,
                "tournament_name": "Ekstraklasa",
                "tournament_flag_url": "c/295.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Rakow Czestochowa",
                "ht_id": 32949,
                "ht_flag_url": "t/32949_504.png",
                "at_name": "Wisla Plock",
                "at_id": 41007,
                "at_flag_url": "t/41007_880.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316361,
                "name": "NK Slaven Belupo - NK Hrvatski Dragovaljac",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 2980,
                "tournament_name": "1. HNL",
                "tournament_flag_url": "c/161.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "NK Slaven Belupo",
                "ht_id": 29976,
                "ht_flag_url": "t/29976.png",
                "at_name": "NK Hrvatski Dragovaljac",
                "at_id": 41780,
                "at_flag_url": "t/41780_426.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316512,
                "name": "FK Spartak Subotica - Cukaricki",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 2993,
                "tournament_name": "Super Liga",
                "tournament_flag_url": "c/326.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "FK Spartak Subotica",
                "ht_id": 41777,
                "ht_flag_url": "t/41777_140.png",
                "at_name": "Cukaricki",
                "at_id": 17080,
                "at_flag_url": "t/17080.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316387,
                "name": "Chabab Mohammedia - Rapide Oued Zem",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 3022,
                "tournament_name": "Botola Pro",
                "tournament_flag_url": "c/246.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Chabab Mohammedia",
                "ht_id": 48557,
                "ht_flag_url": "t/48557.png",
                "at_name": "Rapide Oued Zem",
                "at_id": 33043,
                "at_flag_url": "t/33043.png",
                "score": {
                    "ht_score": "4",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316425,
                "name": "Denizlispor - Boluspor",
                "date": "2022-02-25T18:00:00Z",
                "tournament_id": 3025,
                "tournament_name": "TFF First League",
                "tournament_flag_url": "c/356.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Denizlispor",
                "ht_id": 17565,
                "ht_flag_url": "t/17565_985.png",
                "at_name": "Boluspor",
                "at_id": 14201,
                "at_flag_url": "t/14201_548.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316376,
                "name": "Paderborn - Erzgebirge Aue",
                "date": "2022-02-25T18:30:00Z",
                "tournament_id": 1522,
                "tournament_name": "2. Bundesliga",
                "tournament_flag_url": "c/193.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Paderborn",
                "ht_id": 31101,
                "ht_flag_url": "t/31101.png",
                "at_name": "Erzgebirge Aue",
                "at_id": 19053,
                "at_flag_url": "t/19053.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "3",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316375,
                "name": "Hannover - Holstein Kiel",
                "date": "2022-02-25T18:30:00Z",
                "tournament_id": 1522,
                "tournament_name": "2. Bundesliga",
                "tournament_flag_url": "c/193.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Hannover",
                "ht_id": 22274,
                "ht_flag_url": "t/22274.png",
                "at_name": "Holstein Kiel",
                "at_id": 22945,
                "at_flag_url": "t/22945.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316349,
                "name": "St Pölten - Blau-WeiY Linz",
                "date": "2022-02-25T18:30:00Z",
                "tournament_id": 2985,
                "tournament_name": "Erste Liga",
                "tournament_flag_url": "c/119.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "St Pölten",
                "ht_id": 36834,
                "ht_flag_url": "t/36834.png",
                "at_name": "Blau-WeiY Linz",
                "at_id": 42429,
                "at_flag_url": "t/42429.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316348,
                "name": "Rapid Vienna II - SV Horn",
                "date": "2022-02-25T18:30:00Z",
                "tournament_id": 2985,
                "tournament_name": "Erste Liga",
                "tournament_flag_url": "c/119.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Rapid Vienna II",
                "ht_id": 33041,
                "ht_flag_url": "t/33041.png",
                "at_name": "SV Horn",
                "at_id": 37370,
                "at_flag_url": "t/37370.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316346,
                "name": "FAC Team für Wien - Kapfenberger SV",
                "date": "2022-02-25T18:30:00Z",
                "tournament_id": 2985,
                "tournament_name": "Erste Liga",
                "tournament_flag_url": "c/119.png",
                "status": "Postponed",
                "live_status": "",
                "ht_name": "FAC Team für Wien",
                "ht_id": 19372,
                "ht_flag_url": "t/19372.png",
                "at_name": "Kapfenberger SV",
                "at_id": 24674,
                "at_flag_url": "t/24674.png",
                "score": {
                    "ht_score": "",
                    "at_score": "",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316347,
                "name": "Grazer AK - Austria Vienna II",
                "date": "2022-02-25T18:30:00Z",
                "tournament_id": 2985,
                "tournament_name": "Erste Liga",
                "tournament_flag_url": "c/119.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Grazer AK",
                "ht_id": 21644,
                "ht_flag_url": "t/th_21644_448.png",
                "at_name": "Austria Vienna II",
                "at_id": 12615,
                "at_flag_url": "t/12615_954.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "3",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316416,
                "name": "Maritzburg United - Lamontville Golden Arrows",
                "date": "2022-02-25T18:30:00Z",
                "tournament_id": 2996,
                "tournament_name": "Premier League",
                "tournament_flag_url": "c/381.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Maritzburg United",
                "ht_id": 27663,
                "ht_flag_url": "t/th_27663_974.png",
                "at_name": "Lamontville Golden Arrows",
                "at_id": 25875,
                "at_flag_url": "t/25875_177.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316363,
                "name": "Fremad Amager - Esbjerg",
                "date": "2022-02-25T18:30:00Z",
                "tournament_id": 3001,
                "tournament_name": "NordicBet Ligæn",
                "tournament_flag_url": "c/169.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Fremad Amager",
                "ht_id": 41814,
                "ht_flag_url": "t/41814_214.png",
                "at_name": "Esbjerg",
                "at_id": 19084,
                "at_flag_url": "t/19084.png",
                "score": {
                    "ht_score": "4",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316382,
                "name": "AC Milan - Udinese",
                "date": "2022-02-25T18:45:00Z",
                "tournament_id": 1707,
                "tournament_name": "Serie A",
                "tournament_flag_url": "c/221.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "AC Milan",
                "ht_id": 10202,
                "ht_flag_url": "t/10202.png",
                "at_name": "Udinese",
                "at_id": 39019,
                "at_flag_url": "t/39019.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316362,
                "name": "Vejle-Kolding - AGF Aarhus",
                "date": "2022-02-25T19:00:00Z",
                "tournament_id": 2960,
                "tournament_name": "Superliga",
                "tournament_flag_url": "c/169.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Vejle-Kolding",
                "ht_id": 39795,
                "ht_flag_url": "t/39795.png",
                "at_name": "AGF Aarhus",
                "at_id": 10480,
                "at_flag_url": "t/10480.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316407,
                "name": "Chaves - Benfica II",
                "date": "2022-02-25T19:00:00Z",
                "tournament_id": 2994,
                "tournament_name": "Segunda Liga",
                "tournament_flag_url": "c/296.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Chaves",
                "ht_id": 15995,
                "ht_flag_url": "t/15995.png",
                "at_name": "Benfica II",
                "at_id": 13601,
                "at_flag_url": "t/13601.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316371,
                "name": "Creteil Lusitanos - Sedan",
                "date": "2022-02-25T19:00:00Z",
                "tournament_id": 2997,
                "tournament_name": "Ligue National",
                "tournament_flag_url": "c/187.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Creteil Lusitanos",
                "ht_id": 16883,
                "ht_flag_url": "t/16883.png",
                "at_name": "Sedan",
                "at_id": 35139,
                "at_flag_url": "t/35139.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316369,
                "name": "Chateauroux - Bourg Peronnas",
                "date": "2022-02-25T19:00:00Z",
                "tournament_id": 2997,
                "tournament_name": "Ligue National",
                "tournament_flag_url": "c/187.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Chateauroux",
                "ht_id": 15979,
                "ht_flag_url": "t/th_15979_639.png",
                "at_name": "Bourg Peronnas",
                "at_id": 14411,
                "at_flag_url": "t/14411.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316370,
                "name": "Stade Olympique Choletais - Boulogne",
                "date": "2022-02-25T19:00:00Z",
                "tournament_id": 2997,
                "tournament_name": "Ligue National",
                "tournament_flag_url": "c/187.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Stade Olympique Choletais",
                "ht_id": 36870,
                "ht_flag_url": "t/th_36870_133.png",
                "at_name": "Boulogne",
                "at_id": 14401,
                "at_flag_url": "t/14401.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316372,
                "name": "Stade Briochin - Sete",
                "date": "2022-02-25T19:00:00Z",
                "tournament_id": 2997,
                "tournament_name": "Ligue National",
                "tournament_flag_url": "c/187.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Stade Briochin",
                "ht_id": 47502,
                "ht_flag_url": "t/47502.png",
                "at_name": "Sete",
                "at_id": 47504,
                "at_flag_url": "t/47504.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316367,
                "name": "Avranches - Concarneau",
                "date": "2022-02-25T19:00:00Z",
                "tournament_id": 2997,
                "tournament_name": "Ligue National",
                "tournament_flag_url": "c/187.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Avranches",
                "ht_id": 12677,
                "ht_flag_url": "t/th_12677_139.png",
                "at_name": "Concarneau",
                "at_id": 16584,
                "at_flag_url": "t/th_16584_534.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316373,
                "name": "Villefranche - Red Star",
                "date": "2022-02-25T19:00:00Z",
                "tournament_id": 2997,
                "tournament_name": "Ligue National",
                "tournament_flag_url": "c/187.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Villefranche",
                "ht_id": 42446,
                "ht_flag_url": "t/42446.png",
                "at_name": "Red Star",
                "at_id": 33245,
                "at_flag_url": "t/33245.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316368,
                "name": "Bastia-Borgo - Chambly",
                "date": "2022-02-25T19:00:00Z",
                "tournament_id": 2997,
                "tournament_name": "Ligue National",
                "tournament_flag_url": "c/187.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Bastia-Borgo",
                "ht_id": 42447,
                "ht_flag_url": "t/42447.png",
                "at_name": "Chambly",
                "at_id": 15927,
                "at_flag_url": "t/15927.png",
                "score": {
                    "ht_score": "4",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316364,
                "name": "Helsingør - Nykobing Mors IF",
                "date": "2022-02-25T19:00:00Z",
                "tournament_id": 3001,
                "tournament_name": "NordicBet Ligæn",
                "tournament_flag_url": "c/169.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Helsingør",
                "ht_id": 22605,
                "ht_flag_url": "t/22605_228.png",
                "at_name": "Nykobing Mors IF",
                "at_id": 30345,
                "at_flag_url": "t/30345_187.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316411,
                "name": "U Craiova - FC Targoviste",
                "date": "2022-02-25T19:30:00Z",
                "tournament_id": 1889,
                "tournament_name": "Liga 1",
                "tournament_flag_url": "c/302.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "U Craiova",
                "ht_id": 42456,
                "ht_flag_url": "t/42456.png",
                "at_name": "FC Targoviste",
                "at_id": 19791,
                "at_flag_url": "t/th_19791_892.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316419,
                "name": "FC Aarau - Wil",
                "date": "2022-02-25T19:30:00Z",
                "tournament_id": 1993,
                "tournament_name": "Challenge League",
                "tournament_flag_url": "c/335.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "FC Aarau",
                "ht_id": 10090,
                "ht_flag_url": "t/10090.svg.png",
                "at_name": "Wil",
                "at_id": 40906,
                "at_flag_url": "t/th_40906_138.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316420,
                "name": "Stade Lausanne-Ouchy - FC Vaduz",
                "date": "2022-02-25T19:30:00Z",
                "tournament_id": 1993,
                "tournament_name": "Challenge League",
                "tournament_flag_url": "c/335.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Stade Lausanne-Ouchy",
                "ht_id": 48203,
                "ht_flag_url": "t/48203.png",
                "at_name": "FC Vaduz",
                "at_id": 19813,
                "at_flag_url": "t/19813.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316421,
                "name": "Xamax - Kriens",
                "date": "2022-02-25T19:30:00Z",
                "tournament_id": 1993,
                "tournament_name": "Challenge League",
                "tournament_flag_url": "c/335.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Xamax",
                "ht_id": 47073,
                "ht_flag_url": "t/47073.png",
                "at_name": "Kriens",
                "at_id": 48204,
                "at_flag_url": "t/48204.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316388,
                "name": "RKC Waalwick - Twente",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 1348,
                "tournament_name": "Eredivisie",
                "tournament_flag_url": "c/173.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "RKC Waalwick",
                "ht_id": 33633,
                "ht_flag_url": "t/33633.png",
                "at_name": "Twente",
                "at_id": 38919,
                "at_flag_url": "t/38919.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316355,
                "name": "Nacional Potosi - Guabira",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 2383,
                "tournament_name": "LFPB",
                "tournament_flag_url": "c/134.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Nacional Potosi",
                "ht_id": 29303,
                "ht_flag_url": "t/th_29303_735.png",
                "at_name": "Guabira",
                "at_id": 42483,
                "at_flag_url": "t/0001_odds_logo80.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316390,
                "name": "NAC Breda - PSV Eindhoven II",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3013,
                "tournament_name": "Eerste Divisie",
                "tournament_flag_url": "c/173.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "NAC Breda",
                "ht_id": 29285,
                "ht_flag_url": "t/29285.png",
                "at_name": "PSV Eindhoven II",
                "at_id": 32632,
                "at_flag_url": "t/32632.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316393,
                "name": "Excelsior - Roda JC",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3013,
                "tournament_name": "Eerste Divisie",
                "tournament_flag_url": "c/173.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Excelsior",
                "ht_id": 19327,
                "ht_flag_url": "t/19327.png",
                "at_name": "Roda JC",
                "at_id": 33723,
                "at_flag_url": "t/33723.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316392,
                "name": "Dordrecht - MVV Maastricht",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3013,
                "tournament_name": "Eerste Divisie",
                "tournament_flag_url": "c/173.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Dordrecht",
                "ht_id": 18089,
                "ht_flag_url": "t/18089.png",
                "at_name": "MVV Maastricht",
                "at_id": 29237,
                "at_flag_url": "t/th_29237_639.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316398,
                "name": "FC Oss - Utrecht Youth",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3013,
                "tournament_name": "Eerste Divisie",
                "tournament_flag_url": "c/173.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "FC Oss",
                "ht_id": 30959,
                "ht_flag_url": "t/th_30959_943.png",
                "at_name": "Utrecht Youth",
                "at_id": 39465,
                "at_flag_url": "t/39465_505.png",
                "score": {
                    "ht_score": "4",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316396,
                "name": "De Graafschap - BVV Den Bosch",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3013,
                "tournament_name": "Eerste Divisie",
                "tournament_flag_url": "c/173.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "De Graafschap",
                "ht_id": 17399,
                "ht_flag_url": "t/17399.png",
                "at_name": "BVV Den Bosch",
                "at_id": 15021,
                "at_flag_url": "t/15021.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316394,
                "name": "Emmen - Ajax II",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3013,
                "tournament_name": "Eerste Divisie",
                "tournament_flag_url": "c/173.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Emmen",
                "ht_id": 18872,
                "ht_flag_url": "t/18872_970.png",
                "at_name": "Ajax II",
                "at_id": 10611,
                "at_flag_url": "t/10611.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316395,
                "name": "Volendam - Helmond Sport",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3013,
                "tournament_name": "Eerste Divisie",
                "tournament_flag_url": "c/173.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Volendam",
                "ht_id": 40366,
                "ht_flag_url": "t/40366.png",
                "at_name": "Helmond Sport",
                "at_id": 22597,
                "at_flag_url": "t/th_22597_750.png",
                "score": {
                    "ht_score": "4",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316389,
                "name": "Almere City - VVV Venlo",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3013,
                "tournament_name": "Eerste Divisie",
                "tournament_flag_url": "c/173.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Almere City",
                "ht_id": 11270,
                "ht_flag_url": "t/11270.png",
                "at_name": "VVV Venlo",
                "at_id": 40493,
                "at_flag_url": "t/40493.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316391,
                "name": "ADO Den Haag - Telstar",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3013,
                "tournament_name": "Eerste Divisie",
                "tournament_flag_url": "c/173.png",
                "status": "Cancelled",
                "live_status": "",
                "ht_name": "ADO Den Haag",
                "ht_id": 10362,
                "ht_flag_url": "t/10362.png",
                "at_name": "Telstar",
                "at_id": 37912,
                "at_flag_url": "t/37912.png",
                "score": {
                    "ht_score": "",
                    "at_score": "",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316354,
                "name": "Westerlo - Waasland-Beveren",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3021,
                "tournament_name": "Tweede Klasse",
                "tournament_flag_url": "c/123.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Westerlo",
                "ht_id": 40780,
                "ht_flag_url": "t/40780.png",
                "at_name": "Waasland-Beveren",
                "at_id": 13793,
                "at_flag_url": "t/th_13793_722.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316377,
                "name": "Paksi - Fehervar",
                "date": "2022-02-25T20:00:00Z",
                "tournament_id": 3326,
                "tournament_name": "NB I",
                "tournament_flag_url": "c/211.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Paksi",
                "ht_id": 31159,
                "ht_flag_url": "t/31159_865.png",
                "at_name": "Fehervar",
                "at_id": 46889,
                "at_flag_url": "t/46889.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316422,
                "name": "Schaffhausen - Winterthur",
                "date": "2022-02-25T20:15:00Z",
                "tournament_id": 1993,
                "tournament_name": "Challenge League",
                "tournament_flag_url": "c/335.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Schaffhausen",
                "ht_id": 34976,
                "ht_flag_url": "t/34976_927.png",
                "at_name": "Winterthur",
                "at_id": 40993,
                "at_flag_url": "t/40993_874.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316350,
                "name": "FC Liefering - Austria Lustenau",
                "date": "2022-02-25T20:25:00Z",
                "tournament_id": 2985,
                "tournament_name": "Erste Liga",
                "tournament_flag_url": "c/119.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "FC Liefering",
                "ht_id": 41747,
                "ht_flag_url": "t/th_41747_850.png",
                "at_name": "Austria Lustenau",
                "at_id": 12603,
                "at_flag_url": "t/12603.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "5",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316374,
                "name": "Hoffenheim - VfB Stuttgart",
                "date": "2022-02-25T20:30:00Z",
                "tournament_id": 1521,
                "tournament_name": "Bundesliga",
                "tournament_flag_url": "c/193.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Hoffenheim",
                "ht_id": 22864,
                "ht_flag_url": "t/22864.png",
                "at_name": "VfB Stuttgart",
                "at_id": 39944,
                "at_flag_url": "t/39944.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316405,
                "name": "Widzew Lodz - Arka Gdynia",
                "date": "2022-02-25T20:30:00Z",
                "tournament_id": 2089,
                "tournament_name": "I Liga",
                "tournament_flag_url": "c/295.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Widzew Lodz",
                "ht_id": 40872,
                "ht_flag_url": "t/40872.png",
                "at_name": "Arka Gdynia",
                "at_id": 11951,
                "at_flag_url": "t/11951.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "5",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316403,
                "name": "Legia Warszawa - Wisla Krakow",
                "date": "2022-02-25T20:30:00Z",
                "tournament_id": 2963,
                "tournament_name": "Ekstraklasa",
                "tournament_flag_url": "c/295.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Legia Warszawa",
                "ht_id": 26171,
                "ht_flag_url": "t/26171.png",
                "at_name": "Wisla Krakow",
                "at_id": 41004,
                "at_flag_url": "t/41004.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316353,
                "name": "Beerschot VA - Charleroi",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 2964,
                "tournament_name": "Jupiler Pro League",
                "tournament_flag_url": "c/123.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Beerschot VA",
                "ht_id": 47468,
                "ht_flag_url": "t/47468.png",
                "at_name": "Charleroi",
                "at_id": 15959,
                "at_flag_url": "t/15959.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "3",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316490,
                "name": "UCD - Finn Harps",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 2972,
                "tournament_name": "Premier Division",
                "tournament_flag_url": "c/217.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "UCD",
                "ht_id": 38976,
                "ht_flag_url": "t/38976.png",
                "at_name": "Finn Harps",
                "at_id": 20082,
                "at_flag_url": "t/20082.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316486,
                "name": "Bohemians - Dundalk",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 2972,
                "tournament_name": "Premier Division",
                "tournament_flag_url": "c/217.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Bohemians",
                "ht_id": 14146,
                "ht_flag_url": "t/14146.png",
                "at_name": "Dundalk",
                "at_id": 18332,
                "at_flag_url": "t/18332.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316488,
                "name": "Drogheda United - Shelbourne FC",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 2972,
                "tournament_name": "Premier Division",
                "tournament_flag_url": "c/217.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Drogheda United",
                "ht_id": 18220,
                "ht_flag_url": "t/18220.svg.png",
                "at_name": "Shelbourne FC",
                "at_id": 35486,
                "at_flag_url": "t/35486_376.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316489,
                "name": "St Patricks Athletic - Sligo Rovers",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 2972,
                "tournament_name": "Premier Division",
                "tournament_flag_url": "c/217.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "St Patricks Athletic",
                "ht_id": 36760,
                "ht_flag_url": "t/th_36760_649.png",
                "at_name": "Sligo Rovers",
                "at_id": 35989,
                "at_flag_url": "t/35989.svg.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316487,
                "name": "Derry City - Shamrock Rovers",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 2972,
                "tournament_name": "Premier Division",
                "tournament_flag_url": "c/217.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Derry City",
                "ht_id": 17677,
                "ht_flag_url": "t/17677.png",
                "at_name": "Shamrock Rovers",
                "at_id": 35432,
                "at_flag_url": "t/35432.svg.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316831,
                "name": "Cobh Ramblers - Wexford Youths",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 2978,
                "tournament_name": "First Division",
                "tournament_flag_url": "c/217.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Cobh Ramblers",
                "ht_id": 16426,
                "ht_flag_url": "t/16426.png",
                "at_name": "Wexford Youths",
                "at_id": 40820,
                "at_flag_url": "t/40820.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "3",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316493,
                "name": "Waterford - Bray Wanderers",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 2978,
                "tournament_name": "First Division",
                "tournament_flag_url": "c/217.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Waterford",
                "ht_id": 40657,
                "ht_flag_url": "t/40657.png",
                "at_name": "Bray Wanderers",
                "at_id": 14538,
                "at_flag_url": "t/14538.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316491,
                "name": "Cork City FC - Galway United",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 2978,
                "tournament_name": "First Division",
                "tournament_flag_url": "c/217.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Cork City FC",
                "ht_id": 16697,
                "ht_flag_url": "t/th_16697_526.png",
                "at_name": "Galway United",
                "at_id": 20856,
                "at_flag_url": "t/20856.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316412,
                "name": "Hamilton Academical F.C. - Inverness CT",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 3015,
                "tournament_name": "Championship",
                "tournament_flag_url": "c/310.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Hamilton Academical F.C.",
                "ht_id": 22212,
                "ht_flag_url": "t/22212.png",
                "at_name": "Inverness CT",
                "at_id": 23671,
                "at_flag_url": "t/23671.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316413,
                "name": "Edinburgh City - Cowdenbeath",
                "date": "2022-02-25T20:45:00Z",
                "tournament_id": 3033,
                "tournament_name": "League Two",
                "tournament_flag_url": "c/310.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Edinburgh City",
                "ht_id": 18560,
                "ht_flag_url": "t/18560_561.png",
                "at_name": "Cowdenbeath",
                "at_id": 16813,
                "at_flag_url": "t/th_16813_676.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316365,
                "name": "Southampton - Norwich City",
                "date": "2022-02-25T21:00:00Z",
                "tournament_id": 1415,
                "tournament_name": "Premier League",
                "tournament_flag_url": "c/179.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Southampton",
                "ht_id": 36396,
                "ht_flag_url": "t/0001_odds_logo80.png",
                "at_name": "Norwich City",
                "at_id": 30177,
                "at_flag_url": "t/0001_odds_logo80.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316366,
                "name": "Montpellier - Rennes",
                "date": "2022-02-25T21:00:00Z",
                "tournament_id": 1481,
                "tournament_name": "Ligue 1",
                "tournament_flag_url": "c/187.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Montpellier",
                "ht_id": 28825,
                "ht_flag_url": "t/28825.png",
                "at_name": "Rennes",
                "at_id": 33344,
                "at_flag_url": "t/33344.png",
                "score": {
                    "ht_score": "2",
                    "at_score": "4",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316383,
                "name": "Genoa - Inter",
                "date": "2022-02-25T21:00:00Z",
                "tournament_id": 1707,
                "tournament_name": "Serie A",
                "tournament_flag_url": "c/221.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Genoa",
                "ht_id": 21058,
                "ht_flag_url": "t/21058.png",
                "at_name": "Inter",
                "at_id": 23625,
                "at_flag_url": "t/23625.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316417,
                "name": "Levante - Elche",
                "date": "2022-02-25T21:00:00Z",
                "tournament_id": 1956,
                "tournament_name": "Primera Division",
                "tournament_flag_url": "c/325.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Levante",
                "ht_id": 26326,
                "ht_flag_url": "t/26326.png",
                "at_name": "Elche",
                "at_id": 18781,
                "at_flag_url": "t/18781.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316418,
                "name": "Almeria - Fuenlabrada",
                "date": "2022-02-25T21:00:00Z",
                "tournament_id": 1957,
                "tournament_name": "Segunda Division",
                "tournament_flag_url": "c/325.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Almeria",
                "ht_id": 11272,
                "ht_flag_url": "t/11272.png",
                "at_name": "Fuenlabrada",
                "at_id": 20728,
                "at_flag_url": "t/th_20728_893.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316430,
                "name": "Boston River - Cerro Largo",
                "date": "2022-02-25T21:00:00Z",
                "tournament_id": 2179,
                "tournament_name": "Primera Division",
                "tournament_flag_url": "c/365.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Boston River",
                "ht_id": 47471,
                "ht_flag_url": "t/47471.png",
                "at_name": "Cerro Largo",
                "at_id": 47472,
                "at_flag_url": "t/47472.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "0",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316406,
                "name": "Belenenses - Pacos Ferreira",
                "date": "2022-02-25T21:15:00Z",
                "tournament_id": 1880,
                "tournament_name": "Primeira Liga",
                "tournament_flag_url": "c/296.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Belenenses",
                "ht_id": 13483,
                "ht_flag_url": "t/13483.png",
                "at_name": "Pacos Ferreira",
                "at_id": 31095,
                "at_flag_url": "t/31095.png",
                "score": {
                    "ht_score": "0",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316400,
                "name": "Sporting Cristal - UTC Cajamarca",
                "date": "2022-02-25T21:30:00Z",
                "tournament_id": 2979,
                "tournament_name": "Primera Division",
                "tournament_flag_url": "c/292.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Sporting Cristal",
                "ht_id": 36625,
                "ht_flag_url": "t/36625.png",
                "at_name": "UTC Cajamarca",
                "at_id": 39458,
                "at_flag_url": "t/39458.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316431,
                "name": "Plaza Colonia - Fenix",
                "date": "2022-02-25T23:15:00Z",
                "tournament_id": 2179,
                "tournament_name": "Primera Division",
                "tournament_flag_url": "c/365.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Plaza Colonia",
                "ht_id": 32083,
                "ht_flag_url": "t/32083_502.png",
                "at_name": "Fenix",
                "at_id": 19913,
                "at_flag_url": "t/19913_249.png",
                "score": {
                    "ht_score": "1",
                    "at_score": "1",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            },
            {
                "id": 316343,
                "name": "Defensa y Justicia - Gimnasia LP",
                "date": "2022-02-25T23:15:00Z",
                "tournament_id": 2959,
                "tournament_name": "Primera División",
                "tournament_flag_url": "c/112.png",
                "status": "Completed",
                "live_status": "",
                "ht_name": "Defensa y Justicia",
                "ht_id": 17468,
                "ht_flag_url": "t/17468.png",
                "at_name": "Gimnasia LP",
                "at_id": 21235,
                "at_flag_url": "t/21235.png",
                "score": {
                    "ht_score": "3",
                    "at_score": "2",
                    "score_details": ""
                },
                "sport_id": 1,
                "has_highlights": false,
                "has_stream": false,
                "reversible": false
            }
        ],
        "tournament_table": null,
        "tournament_name": "",
        "tournament_flag_url": "",
        "tournament_start_date": "",
        "Tournament_end_date": "",
        "table_labels": ""
    }
}
"""
